# Imagem base
FROM node:20-alpine

# Instala o pnpm globalmente
RUN npm install -g pnpm

# Define o diretório de trabalho
WORKDIR /app

# Copia SÓ os arquivos de dependência (da raiz)
COPY package.json pnpm-lock.yaml ./

# Instala as dependências
RUN pnpm install

# O docker-compose vai rodar o comando, mas é bom ter um padrão
CMD ["pnpm", "run", "dev"]